;;; --------------------------------------------------------------------
;; free-ids (20)
(test (free-ids (with 'x (num 3) (add (id 'x) (sub (num 3) (id 'x))))) '())
(test (free-ids (with 'x (num 3) (sub (id 'a) (add (num 4) (id 'x))))) '(a))
(test (free-ids (with 'x (num 3) (sub (id 'b) (sub (id 'a) (id 'x))))) '(a b))
(test (free-ids (with 'x (num 3) (sub (id 'a) (sub (id 'b) (add (id 'x) (id 'b)))))) '(a b))
(test (free-ids (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'b) (id 'a))))))) '(a b y))
(test (free-ids (with 'x (id 't) (sub (id 'x) (with 'y (id 'y) (add (id 'x) (sub (id 'b) (id 'a))))))) '(a b t y))
(test (free-ids (with 'x (with 'y (num 3) (sub (id 'x) (id 'y))) (add (id 'x) (id 'y)))) '(x y))
(test (free-ids (add (with 'x (num 10) (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'c) (id 'b))))))) (with 'a (id 'a) (id 'a)))) '(a b c y))
(test (free-ids (add (with 'x (num 10) (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'c) (id 'b))))))) (with 'a (id 'd) (id 'a)))) '(b c d y))
(test (free-ids (add (with 'x (num 10) (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'c) (id 'b))))))) (with 'a (id 'd) (id 'z)))) '(b c d y z))
(test (free-ids (add (with 'x (num 10) (with 'x (id 'z) (sub (id 'x) (with 'z (num 5) (add (id 'z) (sub (id 'a) (id 'b))))))) (with 'z (id 'z) (id 'x)))) '(a b x z))
(test (free-ids (id 'a)) '(a))
(test (free-ids (with 'x (with 'y (id 'x) (id 'x)) (id 'y))) '(x y))
(test (free-ids (with 'x (with 'z (id 'x) (add (id 'z) (id 'y))) (num 3))) '(x y))
(test (free-ids (with 'x (with 'z (id 'x) (add (id 'z) (id 'y))) (with 'y (id 'x) (add (id 'x) (id 'y))))) '(x y))
(test (free-ids (with 'x (num 5) (add (id 'x) (id 'y)))) '(y))
(test (free-ids (sub (sub (id 'x) (id 'a)) (id 't))) '(a t x))
(test (free-ids (with 'a (num 5) (id 'b))) '(b))
(test (free-ids (with 'x (num 5) (add (id 'x) (sub (num 4) (id 'y))))) '(y))
(test (free-ids (with 'x (num 5) (add (id 'z) (id 'y)))) '(y z))

;;; --------------------------------------------------------------------
;; binding-ids (10)
(test (binding-ids (add (num 3) (sub (id 'x) (id 'y)))) '())
(test (binding-ids (with 'y (num 3) (with 'x (id 'x) (id 'y)))) '(x y))
(test (binding-ids (with 'y (num 3) (with 'y (id 'x) (add (id 'x) (id 'y))))) '(y))
(test (binding-ids (with 'y (num 3) (with 'y (with 'x (add (num 3) (id 'y)) (sub (id 'x) (id 'y))) (add (id 'x) (id 'y))))) '(x y))
(test (binding-ids (with 'z (num 3) (with 'w (with 'z (add (num 3) (id 'y)) (sub (id 'x) (id 'y))) (with 'w (id 'y) (add (num 7) (id 'w)))))) '(w z))
(test (binding-ids (with 'x (with 'y (num 3) (add (id 'x) (id 'y))) (add (with 'z (id 'x) (add (num 3) (num 6))) (id 'y)))) '(x y z))
(test (binding-ids (with 'aaa (num 3) (with 'AAA (num 5) (id 'aaa)))) '(AAA aaa))
(test (binding-ids (id 'a)) '())
(test (binding-ids (with 'x (with 'y (id 'x) (id 'x)) (id 'y))) '(x y))
(test (binding-ids (add (with 'c (id 'b) (add (id 'c) (id 'd))) (id 'z))) '(c))

;;; --------------------------------------------------------------------
;; bound-ids (20)
(test (bound-ids (with 'x (num 3) (add (id 'y) (num 3)))) '())
(test (bound-ids (with 'x (num 3) (add (id 'x) (sub (id 'x) (id 'y))))) '(x))
(test (bound-ids (with 'x (num 3) (add (id 'x) (with 'y (num 7) (sub (id 'x) (id 'y)))))) '(x y))
(test (bound-ids (with 'x (num 3) (with 'y (id 'x) (sub (num 3) (id 'y))))) '(x y))
(test (bound-ids (with 'x (num 3) (add (id 'y) (with 'y (id 'x) (sub (num 3) (num 7)))))) '(x))
(test (bound-ids (with 'x (id 'x) (add (id 'y) (with 'y (id 'y) (sub (num 3) (with 'z (num 7) (sub (id 'z) (id 'x)))))))) '(x z))
(test (bound-ids (with 'x (with 'y (num 3) (add (id 'x) (id 'y))) (add (id 'y) (with 'y (id 'y) (sub (num 3) (num 7)))))) '(y))
(test (bound-ids (with 'x (id 'a) (with 'y (id 'b) (with 'z (id 'c) (add (id 'd) (sub (id 'x) (add (id 'y) (id 'z)))))))) '(x y z))
(test (bound-ids (add (with 'x (num 10) (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'c) (id 'b))))))) (with 'a (id 'd) (id 'a)))) '(a x))
(test (bound-ids (add (with 'x (num 10) (with 'x (num 3) (sub (id 'y) (with 'y (num 7) (add (id 'x) (sub (id 'c) (id 'b))))))) (with 'a (id 'd) (id 'z)))) '(x))
(test (bound-ids (add (with 'x (num 3) (id 'y)) (id 'x))) '())
(test (bound-ids (sub (with 'x (num 3) (id 'y)) (with 'y (num 6) (id 'x)))) '())
(test (bound-ids (id 'a)) '())
(test (bound-ids (with 'x (with 'y (id 'x) (id 'x)) (id 'y))) '())
(test (bound-ids (add (add (id 'a) (id 'b)) (add (id 'c) (id 'd)) )) '())
(test (bound-ids (add (with 'c (id 'b) (add (id 'c) (id 'd))) (id 'z))) '(c))
(test (bound-ids (sub (with 'c (id 'b) (add (id 'c) (id 'd))) (id 'z))) '(c))
(test (bound-ids (with 'x (with 'z (id 'x) (add (id 'z) (id 'y))) (num 3))) '(z))
(test (bound-ids (with 'x (with 'z (id 'x) (add (id 'z) (id 'y))) (with 'y (id 'x) (add (id 'x) (id 'y))))) '(x y z))
(test (bound-ids (with 'b (id 'a) (add (num 2) (with 'a (num 8) (add (id 'b) (id 'c)))))) '(b))
