;; given tests (33)
(test (run "{with {f {fun {x} {+ 5 x}}} {f {getField {getField {record {a {record {a 10} {b {- 5 2}}}} {b {getField {record {x 50}} x}}} a} b}}}") 8)
(test (run "{getField {record {a {- 2 1}}} a}") 1)
(test (run "{+ {getField {record {a 10}} a} {getField {record {a 20}} a}}") 30)
(test (run "{with {f {fun {a b c} {record {x a} {y b} {z c} {d 2} {e 3}}}} {getField {f 1 2 3} y}}") 2)
(test (run "{getField {getField {record {a {record {a 10} {b 20}}}} a} a}") 10)
(test (run "{fun {x} x}") 'function)
(test (run "{with {f {fun {a b c d e} {record {a a} {b b} {c c} {d d} {e e}}}} {getField {f 1 2 3 4 5} c}}") 3)
(test (run "{getField {getField {record {a {record {a 10} {b 20}}}} a} b}") 20)
(test (run "{with {y {record {x 1} {y 2} {z 3}}} {getField y y}}") 2)
(test (run "{getField {record {a {+ 1 2}}} a}") 3)
(test/exn (run "{record {z {getField {record {z 0}} y}}}")  "")
(test (run "{with {f {fun {} 4}} {with {g {fun {x} {+ x x}}} {with {x 10} {- {+ x {f}} {g 4}}}}}") 6)
(test (run "{with {y {record {x 1} {y 2} {z 3}}} {getField y z}}") 3)
(test (run "{with {f {fun {a b} {+ {getField a a} b}}} {with {g {fun {x} {+ 5 x}}} {with {x {f {record {a 10} {b 5}} 2}} {g x}}}}") 17)
(test/exn (run "{getField {record {a 10}} b}")  "")
(test (run "{record {a 10}}") 'record)
(test (run "{getField {record {a 10}} a}") 10)
(test (run "{getField {record {a {record {b 10}}}} a}") 'record)
(test (run "{with {x 3} {with {y 5} {getField {record {a x} {b y}} a}}}") 3)
(test (run "{with {f {fun {a b c} {record {a a} {b b} {c c}}}} {getField {f 1 2 3} b}}") 2)
(test (run "{getField {record {r {record {z 0}}}} r}") 'record)
(test (run "{getField {record {a 10} {b {+ 1 2}}} b}") 3)
(test (run "{with {f {fun {x y} {+ x y}}} {f 1 2}}") 3)
(test (run "{with {h {fun {x y z w} {+ x w}}} {h 1 4 5 6}}") 7)
(test (run "{getField {getField {record {a {record {a 10}}}} a} a}") 10)
(test (run "{record {a 10} {b {+ 1 2}}}") 'record)
(test (run "{with {f {fun {} 5}} {+ {f} {f}}}") 10)
(test (run "{with {f {fun {a b} {+ a b}}} {with {g {fun {x} {- x 5}}} {with {x {f 2 5}} {g x}}}}") 2)
(test (run "{getField {getField {record {r {record {z 0}}}} r} z}") 0)
(test (run "{with {g {fun {r} {getField r c}}} {g {record {a 0} {c 12} {b 7}}}}") 12)
(test (run "{with {f {fun {a b c} {record {x a} {y b} {z c} {d 2} {e 3}}}} {getField {f 1 2 3} d}}") 2)
(test/exn (run "{getField {record {b 10} {b {+ 1 2}}} b}")  "")
(test (run "{record {a {- 2 1}}}") 'record)

;; added tests (17)
(test (run "{fun {r l} {- {getField r a} {getField l a}}}") 'function)
(test (run "{{fun {r l} {- {getField r a} {getField l a}}} {record {a 10} {b 20}} {record {a 30} {c 40}}}") -20)
(test (run "{{fun {x} {record {a x}}} 7}") 'record)
(test/exn (run "{fun {x y z x} {+ x x}}")  "")
(test (run "{with {x 3} {+ x {{fun {x y} x} 7 1}}}") 10)
(test (run "{getField {{fun {r l} {record {ra {getField r a}} {la {getField l a}}}} {record {a 10}} {record {a 20}}} la}") 20)
(test (run "{with {e 2} {getField {{fun {a b c d} {record {a a} {b b} {c c} {d d} {e e}}} 3 4 5 6} e}}") 2)
(test (run "{{fun {x} {getField {record {a x}} a}} 7}") 7)
(test (run "{with {a 1} {+ {getField {record {a 2}} a} a}}") 3)
(test/exn (run "{{fun {x y z w} {+ x x}} 1 2 3}")  "")
(test (run "{getField {{fun {r l} {record {ra {getField r a}} {la {getField l a}}}} {record {a 10}} {record {a 20}}} ra}") 10)
(test/exn (run "{{fun {x} {getField {record {a x} {x a}} a}} 7}")  "")
(test (run "{with {e 2} {getField {{fun {a b c d} {record {a a} {b b} {c c} {d d} {e e}}} 3 4 5 6} a}}") 3)
(test (run "{with {a 1} {getField {record {a 2}} a}}") 2)
(test (run "{with {a 1} {record {a 1}}}") 'record)
(test (run "{fun {x} {record {a x}}}") 'function)
(test (run "{fun {a b c d} {record {a a} {b b} {c c} {d d}}}") 'function)
